DROP TABLE history IF EXISTS;
DROP TABLE user_role IF EXISTS;
DROP TABLE role_data IF EXISTS;
DROP TABLE activity IF EXISTS;
DROP TABLE user_data IF EXISTS;
DROP TABLE answer IF EXISTS;
DROP TABLE question IF EXISTS;
DROP TABLE quiz IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE user_data
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    username         VARCHAR(255)            NOT NULL,
    email            VARCHAR(255)            NOT NULL,
    password         VARCHAR(255)            NOT NULL
);

CREATE TABLE role_data
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name         VARCHAR(255)            NOT NULL
);

CREATE TABLE user_role
(
    user_id         INTEGER NOT NULL,
    role_id         INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user_data (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role_data (id) ON DELETE CASCADE
);

CREATE TABLE activity
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    activated        INTEGER           NOT NULL,
    uuid             VARCHAR(255)      NOT NULL,
    user_id          INTEGER           NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user_data (id) ON DELETE CASCADE
);

CREATE TABLE quiz
(
    id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    description VARCHAR(255) NOT NULL,
    published BOOLEAN NOT NULL,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE question
(
    id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    quiz_id     INTEGER      NOT NULL,
    FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE
);

CREATE TABLE answer
(
    id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    question_id     INTEGER      NOT NULL,
    FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE
);

CREATE TABLE history
(
    id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    is_correct BOOLEAN NOT NULL,
    answer_id INTEGER NOT NULL,
    question_id     INTEGER      NOT NULL,
    quiz_id     INTEGER      NOT NULL,
    user_id     INTEGER      NOT NULL,
    FOREIGN KEY (answer_id) REFERENCES answer (id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE,
    FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user_data (id) ON DELETE CASCADE
);


